# Generated by Django 5.0.4 on 2024-04-26 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Category image')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name_plural': 'Add to category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('size', models.CharField(blank=True, choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small'), ('Tiny', 'Tiny')], max_length=100, null=True)),
                ('department', models.CharField(blank=True, choices=[('Fresh Meat', 'Fresh Meat'), ('Vegetables', 'Vegetables'), ('Fruit & Nut Gifts', 'Fruit & Nut Gifts'), ('Fresh Berries', 'Fresh Berries'), ('Ocean Foods', 'Ocean Foods'), ('Butter & Eggs', 'Butter & Eggs'), ('Fastfood', 'Fastfood'), ('Fresh Onion', 'Fresh Onion'), ('Papaya & Crisps', 'Papaya & Crisps'), ('Oatmeal', 'Oatmeal'), ('Fresh Bananas', 'Fresh Bananas')], max_length=200, null=True)),
                ('description', models.CharField(max_length=300, verbose_name='Short Description')),
                ('Products_Infomation', models.TextField(max_length=1000, verbose_name='Product Information')),
                ('image', models.ImageField(upload_to='Product Image')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
