# Generated by Django 5.0.4 on 2024-05-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_billing_detailss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_detailss',
            old_name='address',
            new_name='adrs',
        ),
        migrations.RenameField(
            model_name='billing_detailss',
            old_name='country',
            new_name='cntry',
        ),
        migrations.RenameField(
            model_name='billing_detailss',
            old_name='city',
            new_name='cty',
        ),
        migrations.RenameField(
            model_name='billing_detailss',
            old_name='email',
            new_name='emil',
        ),
        migrations.RenameField(
            model_name='billing_detailss',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='billing_detailss',
            old_name='last_name',
            new_name='l_name',
        ),
        migrations.RenameField(
            model_name='billing_detailss',
            old_name='local_address',
            new_name='lcl_adrs',
        ),
        migrations.RenameField(
            model_name='billing_detailss',
            old_name='phone',
            new_name='phne',
        ),
        migrations.RenameField(
            model_name='billing_detailss',
            old_name='state',
            new_name='stte',
        ),
        migrations.RenameField(
            model_name='billing_detailss',
            old_name='user',
            new_name='usr',
        ),
        migrations.RenameField(
            model_name='billing_detailss',
            old_name='zip',
            new_name='zp',
        ),
    ]
